### PR TITLE
Update logic.js

### PR DESCRIPTION
**Pull request by synthgab**
- Adding a few other tracking tokens I saw : aff_ , mtrck , xtor , xtref , xtrck
- Adding the case of some sneaky web sites which don't use URL parameters but anchors (see example below):
  http://www.leparisien.fr/<category>/<article_title>.php#xtor=AD-1481423552&xtref=https%3A%2F%2Fwww.facebook.com%2F

### CODE REVIEW

**Comment by rudiedirkx** [comment]
Is there no way to combine that? Seems like a lot of double code now... That's why you added `\#`, isn't it?

**Comment by synthgab** [comment]
Hi,

Indeed, I also think this can be merged together, but I'm not sure how the split would behave.

I'll work on that, though; and thanks for the review.

Gab

**Comment by synthgab** [comment]
Hi,

I rewritten most of the logic code, but there is no more duplicate code, and I tested a lot of different cases and did not face any issue.

Thanks for this extension, anyway, Chrome is really missing this kind of stuff.

**Comment by rudiedirkx** [comment]
1 bug (already existed);

`http://example.com/#utm_source=foo&keep=1` becomes
`http://example.com/?keep=1`, but it should become
`http://example.com/#keep=1`

Will fix and commit. I've also added test cases in `tests/cases.js`, so add more if you find any edge cases etc.

**Comment by rudiedirkx** [comment]
Fixed in 40e954b. Thanks!

**Pull request closed without merging**
